server:
    name: sidecar                   # 服务名称
    port: 8081                      # 服务启动端口
# 代理配置
    #http://localhost:19029
    #http://localhost:8080
    #http://rest-service-http.bullyun-blue.svc.cluster.local:8080
    #http://boss-service-http.bullyun-blue.svc.cluster.local:8080
    #http://video-gb-service-http.bullyun-blue.svc.cluster.local:8080
    #http://127.0.0.1:8080
proxy:
    target: http://localhost:19029   # 目标地址
    dialer:
        timeout: 10s                 # 连接超时时间（秒）
        keep_alive: 30s              # 保持连接的时间（秒）
    transport:
        max_idle_conns: 1000          # 最大空闲连接数
        idle_conn_timeout: 90s       # 空闲连接的超时时间（秒）
        tls_handshake_timeout: 10s   # TLS 握手超时时间（秒）
    flushInterval: 100s              # 设置数据刷新间隔（秒）
# 黑名单默认配置
blacklist:
    defaultRate_limit : 100          # 默认限流
    config_reload_interval : 10s     # 配置重载间隔（秒）
# apollo配置
apollo:                              # apollo配置
    AppID: bullyun-v2                # 应用ID
    Cluster: PRO                     # 集群名称
    IP: http://10.10.4.80:8080       # apollo地址 http://10.10.4.80:8080
    NamespaceName: sidecar           # 命名空间名称
    IsBackupConfig: true             # 是否备份配置
# 日志配置
logger :
    log_level: 0                     # 日志等级 debug = -1, info = 0, warn = 1, error = 2
    log_path: ./logs                 # 日志文件路径
    log_name: sidecar-service.log    # 日志文件名称
    log_max_size: 10                 # 最大文件大小（MB）
    log_max_backups: 3               # 最大备份文件数
    log_max_age: 7                   # 日志保留天数
    log_compress: true               # 是否压缩备份文件
# 机器人配置
robot :
    enable: true                     # 是否开启机器人报警
    webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=df77a0d9-9648-4b30-8716-03835dbab4a0


