apollo:                              # apollo配置
    # 应用ID
    AppID: rest-service
    # 集群名称
    Cluster: PRO
    # apollo地址
    Meta: http://10.10.4.80:8080
    # 通用命名空间
    CommonNamespaceName: mongodb
    # 服务定制的命名空间 默认可不填
    NamespaceName: