apollo:                              # apollo配置
    # 应用ID
    AppID: rest-service
    # 集群名称
    Cluster: PRO
    # apollo地址
    Meta: http://10.10.4.80:8080
    # 通用命名空间
    CommonNamespaceName: mongodb
    # 服务定制的命名空间 默认可不填
    NamespaceName:

# 日志配置
logger :
    log_level: 0                     # 日志等级 debug = -1, info = 0, warn = 1, error = 2
    log_path: ./logs                 # 日志文件路径
    log_name: xx.log                 # 日志文件名称
    log_max_size: 10                 # 最大文件大小（MB）
    log_max_backups: 3               # 最大备份文件数
    log_max_age: 7                   # 日志保留天数
    log_compress: true               # 是否压缩备份文件